routes/web.php
<?php

use App\Product;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//default routes for unauthenticated users 
Route::get('/','HomePageController@index');

Route::get('/details/{product}','ProductController@Webshow')->name('product_detail');

Route::any('/filter','ProductController@SearchProduct')->name('filter');

Auth::routes();

Route::get('/home', 'Dashboard\DashboardController@index')->name('home')->middleware(['auth']);

Route::group(['middleware' => ['auth']], function () {
    //category route
         Route::resource('category', 'CategoryController');
    //subcategory route
        Route::resource('subcategory','SubCategoryController');
    //fornecedores
        Route::resource('fornecedor', 'FornecedorController');        
    //post route
        Route::resource('post', 'PostController');
        Route::resource('product', 'ProductController');
    //favorites routes
        Route::get('favorites','FavoriteController@index')->name('favorites');
        Route::get('favorite/{product}/{user}','FavoriteController@destroy')->name('favorite_delete');

        Route::get('/favorites/{product}', 'FavoriteController@add')->name('favorite');
    //orders or compras routes        
        Route::resource('order', 'OrderController');
        Route::post('orderWeb','OrderController@storeWeb')->name('order.storeWeb');
        Route::get('/comprar/{product}', 'OrderController@buyOne')->name('comprar');
        Route::post('carts/order','OrderController@storeCart')->name('order.cart');
    //carts routes
        Route::get('/carts','CartController@index')->name('carts');
        Route::get('/cart/{product}','CartController@add')->name('cart');
        Route::get('/getCarts','CartController@getCarts')->name('getCarts');
        Route::get('cart/remove/{cart}', 'CartController@destroy')->name('delete_cart');
        Route::get('/cartx/freeze', 'CartController@freeze')->name('empty_cart');
        

    //tag route
        Route::resource('tag', 'TagController');
    //payment route
        Route::resource('payment', 'PaymentController');
    //status route
        Route::resource('status', 'StatusController');
    //user route
        Route::resource('user', 'Auth\UserController');
        Route::get('profile','Auth\UserController@profile')->name('user.profile');
    //role route
        Route::resource('role', 'RoleController');
        Route::get('/index','RoleController@Webindex');
    //Developers route
        Route::get('developers','DevelopersController@index')->name('developers.index');     


    Route::get('buylog', function () {
        return view('backend.dashboard.buyLogs'); 
    })->name('buylogs');
    
    Route::get('/agendar/{product}', 'AgendarController@create')->name('agendar');
    Route::get('/agendar', 'AgendarController@store')->name('agendar.store');
    Route::get('/agendar/{id}', 'AgendarController@update')->name('agendar.update');
    Route::post('/agendar/delete/{id}', 'AgendarController@delete')->name('agendar.destroy');
});


Route::group(['middleware' => ['auth','it']], function () {
    
});

Route::group(['middleware' => ['auth']], function () {
    
});

Route::group(['middleware' => ['auth']], function () {
    
});

Route::group(['middleware' => ['auth']], function () {
    
});

Route::group(['middleware' => ['auth']], function () {
    
});

app/Http/Controllers/Dashboard/DashboardController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
//use Illuminate\Http\Request;

class DashboardController extends Controller
{
    /**
     * Handle the incoming request.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('backend.dashboard.dashboard');
    }
}

resources/views/backend/dashboard/category.blade.php
@extends('backend.layout.app')
@section('content')
    @push('css')
        <link href="{{ asset('css/app.css') }}">
        <link href="'{{ asset('dashboard/datatables/dataTables.bootstrap4.css') }}'">
        <link href="https://cdn.datatables.net/1.10.23/css/jquery.dataTables.min.css">
    @endpush

    <div class="container">
        <div class="card">

            <div class="card-header">
                <h4>Categories Table</h4> <a href="#" class="btn btn-icon icon-left btn-info" id="modal-5"><i
                        class="fas fa-info-circle"></i> Create category</a>

            </div>
            <div class="card-body p-4">
                <div class="table-responsive p-0 " style="overflow:hidden ">
                    <table id="example" class="table table-striped v_center" style="width:100%; ">
                        <thead>
                            <tr>
                                <th class="text-center">
                                    <i class="fas fa-th"></i>
                                </th>
                                <th>Nome da categoria</th>
                                <th>Número de subcategorias</th>
                                <th>Created at</th>
                                <th>Edit</th>
                                <th>Delete</th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach ($categories as $category)
                                <tr>
                                    <td>{{ $category->id }}</td>
                                    <td>{{ $category->name }}</td>
                                    <td>{{ $category->subCategories->count() }}</td>
                                    <td>
                                        {{ (new DateTime($category->created_at))->format('d-m-Y') }}
                                    </td>
                                    <td>
                                        <button class="btn btn-icon icon-left btn-warning update_modal_{{ $category->id }}"
                                            obj="{{ $category->id }}"> <i class="fas fas fa-edit"></i>Edit</button>
                                    </td>
                                    <td>
                                        <form action="{{ route('category.destroy', ['category' => $category->id]) }}"
                                            id="delete_{{ $category->id }}" method="POST">
                                            @csrf
                                            @method('DELETE')
                                            <input type="hidden" name="id" value="{{ $category->id }}">
                                            <!--input type="submit" class="btn btn-icon icon-left btn-danger" value="Delete"-->
                                            <button class="btn btn-icon icon-left btn-danger" type="submit"><i
                                                    class="fas fas fa-trash"></i>Delete</button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                        <tfoot>
                            <tr>
                                <th class="text-center">
                                    <i class="fas fa-th"></i>
                                </th>
                                <th>Nome da categoria</th>
                                <th>Número de subcategorias</th>
                                <th>Created at</th>
                                <th>Edit</th>
                                <th>Delete</th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>

    </div>

    <form action="{{ route('category.store') }}" method="post" id="form_category">
        @csrf
        <input type="text" class="form-control" name="name" required value="{{ old('name') }}" placeholder="Create Category"
            style="background:rgb(226, 226, 226)">
    </form>
    @push('js')
        <!-- JS Libraies -->
        <script src="{{ asset('dashboard/assets/modules/jquery-ui/jquery-ui.min.js') }}"></script>
        <!-- Page Specific JS File -->

        <script src="{{ asset('dashboard/datatables/jquery.dataTables.js') }}">
        </script>
        <script src="{{ asset('dashboard/datatables/dataTables.bootstrap4.min.js') }}"></script>
        <script src="{{ asset('dashboard/js/page/components-table.js') }}"></script>
        <script>
            $('#modal-5').fireModal({
                title: 'New category',
                body: $('#form_category'),
                buttons: [{
                    text: 'Save',
                    submit: true,
                    class: 'btn btn-primary btn-shadow',
                    handler: function(modal) {
                        console.log(modal);
                    }
                }]
            });


        </script>
        <script>
            $(document).ready(function() {
                $('#example').DataTable({
                    "bPaginate": true,
                    "bLengthChange": false,
                    "bFilter": true,
                    "bInfo": false,
                    "bAutoWidth": true,
                    "language": {
                        "search": "_INPUT_",
                        "searchPlaceholder": "Pesquisar"
                    },
                    "showNEntries": false,
                    "info": false,
                    "lengthMenu": 10
                });
                $('#example_filter').addClass('input-group');
                $('#example_filter input').addClass('form-control mr-0');
                $('#example_filter input').removeClass('form-control-sm');
                $('#example_paginate').addClass('float-right');
                $('#example_filter input').parent().css('width', '100%');
                //.addCss('dary');

            });

        </script>

        @foreach ($categories as $category)
            <form action="{{ route('category.update', $category->id) }}" method="post"
                id="form_category_update_{{ $category->id }}">
                @method('PUT')
                @csrf
                <input type="text" class="form-control" name="name" required value="{{ $category->name }}"
                    placeholder="Edit Category" style="background:rgb(226, 226, 226)">
            </form>
            <script>
                $('.update_modal_{{ $category->id }}').fireModal({
                    title: 'Edit category',
                    body:$('#form_category_update_{{ $category->id }}'),
                    buttons: [{
                        text: 'Update',
                        submit: true,
                        class: 'btn btn-primary btn-shadow',
                        handler: function(modal) {
                            console.log(modal);
                        }
                    }]
                });

            </script>
        @endforeach
    @endpush
@endsection

resources/views/backend/dashboard/dashboard.blade.php
@extends('backend.layout.app')

@section('content')
<div class="container py-2">
    <div class="row justify-content-center">
        <div class="col-md-12 ">
             
        </div>
    </div>
</div>
@endsection

resources/views/backend/dashboard/fornecedor.blade.php
@extends('backend.layout.app')
@section('content')
    @push('css')
        <link href="{{ asset('css/app.css') }}">
        <link href="'{{ asset('dashboard/datatables/dataTables.bootstrap4.css') }}'">
        <link href="https://cdn.datatables.net/1.10.23/css/jquery.dataTables.min.css">
    @endpush

    <div class="container">
        <div class="card">

            <div class="card-header">
                <h4>Fornecedores Table</h4> <a href="#" class="btn btn-icon icon-left btn-info" id="modal-5"><i
                        class="fas fa-car-side"></i> Create Fornecedor</a>
            </div>
            <div class="card-body p-4">
                <div class="table-responsive p-0 " style="overflow:hidden ">
                    <table id="example" class="table table-striped v_center" style="width:100%; ">
                        <thead>
                            <tr>
                                <th class="text-center">
                                    <i class="fas fa-th"></i>
                                </th>
                                <th>Nome do Fornecedor</th>
                                <th>Contact</th>
                                <th>Email</th>
                                <th>Created at</th>
                                <th>Edit</th>
                                <th>Delete</th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach ($fornecedors as $fornecedor)
                                <tr>
                                    <td>{{ $fornecedor->id }}</td>
                                    <td>{{ $fornecedor->name }}</td>
                                    <td>{{ $fornecedor->contact }}</td>
                                    <td>{{ $fornecedor->email }}</td>
                                    <td>
                                        {{ (new DateTime($fornecedor->created_at))->format('d-m-Y') }}
                                    </td>
                                    <td>
                                        <button class="btn btn-icon icon-left btn-warning update_modal_{{ $fornecedor->id }}"
                                            obj="{{ $fornecedor->id }}"> <i class="fas fas fa-edit"></i>Edit</button>
                                    </td>
                                    <td>
                                        <form action="{{ route('fornecedor.destroy', ['fornecedor' => $fornecedor->id]) }}"
                                            id="delete_{{ $fornecedor->id }}" method="POST">
                                            @csrf
                                            @method('DELETE')
                                            <input type="hidden" name="id" value="{{ $fornecedor->id }}">
                                            <!--input type="submit" class="btn btn-icon icon-left btn-danger" value="Delete"-->
                                            <button class="btn btn-icon icon-left btn-danger" type="submit"><i
                                                    class="fas fas fa-trash"></i>Delete</button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                        <tfoot>
                            <tr>
                                <th class="text-center">
                                    <i class="fas fa-th"></i>
                                </th>
                                <th>Nome do fornecedor</th>
                                <th>Contact</th>
                                <th>Email</th>
                                <th>Created at</th>
                                <th>Edit</th>
                                <th>Delete</th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>

    </div>

    <form action="{{ route('fornecedor.store') }}" method="post" id="form_fornecedor">
        @csrf
        <div class="form-group">
            <div class="row">
              
                <div class="col-sm-12">
                      <label for="name">Name</label>
                    <input type="text" class="form-control" name="name" required value="{{ old('name') }}" placeholder="Create fornecedor"
            style="background:rgb(226, 226, 226)">
                </div>
                
                <div class="col-sm-12 py-2">
                    <label for="contact">Contact</label>
                    <input type="tel" class="form-control" name="contact" required value="{{ old('contact') }}" placeholder="Contact"
            style="background:rgb(226, 226, 226)">
                </div>
                
                <div class="col-sm-12 py-2">
                <label for="email">Email</label>
                    <input type="email" class="form-control" name="email"  value="{{ old('email') }}" placeholder="Email"
            style="background:rgb(226, 226, 226)">
                </div>
            </div>
        </div>
        
    </form>
    @push('js')
        <!-- JS Libraies -->
        <script src="{{ asset('dashboard/assets/modules/jquery-ui/jquery-ui.min.js') }}"></script>
        <!-- Page Specific JS File -->

        <script src="{{ asset('dashboard/datatables/jquery.dataTables.js') }}">
        </script>
        <script src="{{ asset('dashboard/datatables/dataTables.bootstrap4.min.js') }}"></script>
        <script src="{{ asset('dashboard/js/page/components-table.js') }}"></script>
        <script>
            $('#modal-5').fireModal({
                title: 'New Fornecedor',
                body: $('#form_fornecedor'),
                buttons: [{
                    text: 'Save',
                    submit: true,
                    class: 'btn btn-primary btn-shadow',
                    handler: function(modal) {
                        console.log(modal);
                    }
                }]
            });


        </script>
        <script>
            $(document).ready(function() {
                $('#example').DataTable({
                    "bPaginate": true,
                    "bLengthChange": false,
                    "bFilter": true,
                    "bInfo": false,
                    "bAutoWidth": true,
                    "language": {
                        "search": "_INPUT_",
                        "searchPlaceholder": "Pesquisar"
                    },
                    "showNEntries": false,
                    "info": false,
                    "lengthMenu": 10
                });
                $('#example_filter').addClass('input-group');
                $('#example_filter input').addClass('form-control mr-0');
                $('#example_filter input').removeClass('form-control-sm');
                $('#example_paginate').addClass('float-right');
                $('#example_filter input').parent().css('width', '100%');
                //.addCss('dary');

            });

        </script>

        @foreach ($fornecedors as $fornecedor)
            <form action="{{ route('fornecedor.update', $fornecedor->id) }}" method="post"
                id="form_fornecedor_update_{{ $fornecedor->id }}">
                @method('PUT')
                @csrf
                        <div class="form-group">
                            
                    <div class="row">
                        <div class="col-sm-12">
                            <label for="name">Name</label>
                            <input type="text" class="form-control" name="name" required value="{{ $fornecedor->name }}" placeholder="Create fornecedor"
                    style="background:rgb(226, 226, 226)">
                        </div>
                        
                        <div class="col-sm-12 py-2">
                            <label for="contact">Contact</label>
                            <input type="tel" class="form-control" name="contact" required value="{{ $fornecedor->contact }}" placeholder="Contact"
                    style="background:rgb(226, 226, 226)">
                        </div>
                        
                        <div class="col-sm-12 py-2">
                            <label for="email">Email</label>
                            <input type="email" class="form-control" name="email"  value="{{ $fornecedor->email }}" placeholder="Email"
                    style="background:rgb(226, 226, 226)">
                        </div>
                    </div>
                </div>
            </form>
            <script>
                $('.update_modal_{{ $fornecedor->id }}').fireModal({
                    title: 'Edit fornecedor',
                    body:$('#form_fornecedor_update_{{ $fornecedor->id }}'),
                    buttons: [{
                        text: 'Update',
                        submit: true,
                        class: 'btn btn-primary btn-shadow',
                        handler: function(modal) {
                            console.log(modal);
                        }
                    }]
                });

            </script>
        @endforeach
    @endpush
@endsection

resources/views/backend/dashboard/payment.blade.php
@extends('backend.layout.app')
@section('content')
    @push('css')
        <link href="{{ asset('css/app.css') }}">
        <link href="'{{ asset('dashboard/datatables/dataTables.bootstrap4.css') }}'">
        <link href="https://cdn.datatables.net/1.10.23/css/jquery.dataTables.min.css">
    @endpush

    <div class="container">
        <div class="card">

            <div class="card-header">
                <h4>Payment Table</h4> <a href="#" class="btn btn-icon icon-left btn-info" id="modal-5"><i
                        class="fas fa-money-bill"></i> Create Payment</a>

            </div>
            <div class="card-body p-4">
                <div class="table-responsive p-0 " style="overflow:hidden ">
                    <table id="example" class="table table-striped v_center" style="width:100%; ">
                        <thead>
                            <tr>
                                <th class="text-center">
                                    <i class="fas fa-th"></i>
                                </th>
                                <th>Nome da Payment</th>
                                <th>Created at</th>
                                <th>Edit</th>
                                <th>Delete</th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach ($payments as $payment)
                                <tr>
                                    <td>{{ $payment->id }}</td>
                                    <td>{{ $payment->name }}</td>
                                    <td>
                                        {{ (new DateTime($payment->created_at))->format('d-m-Y') }}
                                    </td>
                                    <td>
                                        <button class="btn btn-icon icon-left btn-warning update_modal_{{ $payment->id }}"
                                            obj="{{ $payment->id }}"> <i class="fas fas fa-edit"></i>Edit</button>
                                    </td>
                                    <td>
                                        <form action="{{ route('payment.destroy', ['payment' => $payment->id]) }}"
                                            id="delete_{{ $payment->id }}" method="POST">
                                            @csrf
                                            @method('DELETE')
                                            <input type="hidden" name="id" value="{{ $payment->id }}">
                                            <!--input type="submit" class="btn btn-icon icon-left btn-danger" value="Delete"-->
                                            <button class="btn btn-icon icon-left btn-danger" type="submit"><i
                                                    class="fas fas fa-trash"></i>Delete</button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                        <tfoot>
                            <tr>
                                <th class="text-center">
                                    <i class="fas fa-th"></i>
                                </th>
                                <th>Nome da payment</th>
                                <th>Created at</th>
                                <th>Edit</th>
                                <th>Delete</th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>

    </div>

    <form action="{{ route('payment.store') }}" method="post" id="form_payment">
        @csrf
        <input type="text" class="form-control" name="name" required value="{{ old('name') }}" placeholder="Create Payment"
            style="background:rgb(226, 226, 226)">
    </form>
    @push('js')
        <!-- JS Libraies -->
        <script src="{{ asset('dashboard/assets/modules/jquery-ui/jquery-ui.min.js') }}"></script>
        <!-- Page Specific JS File -->

        <script src="{{ asset('dashboard/datatables/jquery.dataTables.js') }}">
        </script>
        <script src="{{ asset('dashboard/datatables/dataTables.bootstrap4.min.js') }}"></script>
        <script src="{{ asset('dashboard/js/page/components-table.js') }}"></script>
        <script>
            $('#modal-5').fireModal({
                title: 'New Payment',
                body: $('#form_payment'),
                buttons: [{
                    text: 'Save',
                    submit: true,
                    class: 'btn btn-primary btn-shadow',
                    handler: function(modal) {
                        console.log(modal);
                    }
                }]
            });


        </script>
        <script>
            $(document).ready(function() {
                $('#example').DataTable({
                    "bPaginate": true,
                    "bLengthChange": false,
                    "bFilter": true,
                    "bInfo": false,
                    "bAutoWidth": true,
                    "language": {
                        "search": "_INPUT_",
                        "searchPlaceholder": "Pesquisar"
                    },
                    "showNEntries": false,
                    "info": false,
                    "lengthMenu": 10
                });
                $('#example_filter').addClass('input-group');
                $('#example_filter input').addClass('form-control mr-0');
                $('#example_filter input').removeClass('form-control-sm');
                $('#example_paginate').addClass('float-right');
                $('#example_filter input').parent().css('width', '100%');
                //.addCss('dary');

            });

        </script>

        @foreach ($payments as $payment)
            <form action="{{ route('payment.update', $payment->id) }}" method="post"
                id="form_payment_update_{{ $payment->id }}">
                @method('PUT')
                @csrf
                <input type="text" class="form-control" name="name" required value="{{ $payment->name }}"
                    placeholder="Edit Payment" style="background:rgb(226, 226, 226)">
            </form>
            <script>
                $('.update_modal_{{ $payment->id }}').fireModal({
                    title: 'Edit Payment',
                    body:$('#form_payment_update_{{ $payment->id }}'),
                    buttons: [{
                        text: 'Update',
                        submit: true,
                        class: 'btn btn-primary btn-shadow',
                        handler: function(modal) {
                            console.log(modal);
                        }
                    }]
                });

            </script>
        @endforeach
    @endpush
@endsection

resources/views/backend/dashboard/profile.blade.php
@extends('backend.layout.app')
@section('content')
    {{ $user }}
@endsection